title: Álvaro Juan Ciriaco
logo: /assets/img/logo.png
description: Profesor de Grado Superior DAM
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
linkedin: https://www.linkedin.com/in/álvaro-juan-ciriaco-zgz/