title: Álvaro Juan Ciriaco
logo: /assets/img/logo.png
description: Profesor de Grado Superior DAM
[Link to another page](./another-page.html).
[Link to another page](./another-page.html).
[Link to another page](./another-page.html).
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal